# -*- coding: utf-8 -*-
"""Copy of SQA Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJ02VuxU4AFADUtrg3mERaV4ghEQF-3W

STEP 0: Import Libraries (Visible & Standard)
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve
)

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from imblearn.over_sampling import SMOTE

"""STEP 1: Load Dataset (Evaluator Can See Data)"""

df = pd.read_csv("data/cm1.csv")

print("Dataset Shape:", df.shape)
df.head()

"""STEP 2: Understand Quality Metrics (EDA – SQA Insight)


2.1 Defect Distribution (Class Imbalance – SQA Issue)
"""

df['defects'].value_counts()

sns.countplot(x=df['defects'] > 0)
plt.title("Defective vs Non-Defective Modules")
plt.xlabel("Defect Present")
plt.ylabel("Number of Modules")
plt.show()

"""2.2 LOC vs Defects (Quality Metric Relationship)"""

plt.figure(figsize=(6,4))
sns.boxplot(x=df['defects'] > 0, y=df['loc'])
plt.title("Lines of Code vs Defect Presence")
plt.xlabel("Defective Module")
plt.ylabel("Lines of Code")
plt.show()

"""STEP 3: Preprocessing (Quality-Driven)

3.1 Create Binary Defect Label
"""

df['defective'] = df['defects'].apply(lambda x: 1 if x > 0 else 0)

"""3.2 Feature & Label Split"""

X = df.drop(columns=['defects', 'defective'])
y = df['defective']

"""3.3 Feature Scaling"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

"""3.4 Handle Class Imbalance"""

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_scaled, y)

print("After SMOTE:", np.bincount(y_res))

"""STEP 4: Train–Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X_res, y_res, test_size=0.3, random_state=42
)

"""STEP 5: Train Models (Visible Comparison)"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=200)
}

"""STEP 6: Model Evaluation (SQA Metrics)"""

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:,1]

    print("\n", "="*50)
    print("MODEL:", name)
    print(classification_report(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_prob))

"""STEP 7: Confusion Matrix"""

best_model = models["Random Forest"]
y_pred = best_model.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix – Defect Prediction")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""STEP 8: ROC Curve (Risk Discrimination)"""

y_prob = best_model.predict_proba(X_test)[:,1]
fpr, tpr, _ = roc_curve(y_test, y_prob)

plt.plot(fpr, tpr, label="Random Forest")
plt.plot([0,1], [0,1], '--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve – Defect Prediction")
plt.legend()
plt.show()

"""STEP 9: Defect Risk Ranking (Final SQA Output)"""

df['defect_risk_score'] = best_model.predict_proba(X_scaled)[:,1]

ranked_modules = df.sort_values(
    by='defect_risk_score', ascending=False
)

ranked_modules[['defect_risk_score']].head(10)

"""STEP 10: Save Results and implement Defect Removal Effectiveness (DRE)"""

ranked_modules.to_csv("cm1_defect_risk_results.csv", index=False)
print("Results saved for QA prioritization.")

TP = cm[1, 1]
FN = cm[1, 0]
DRE = TP / (TP + FN)

print(f"Defect Removal Effectiveness (DRE): {DRE:.2f}")

import joblib

# The 'best_model' variable in your code is the Random Forest
model_filename = "defect_model.pkl"
joblib.dump(best_model, model_filename)

# Download to your local computer
from google.colab import files
files.download(model_filename)

import joblib
from google.colab import files

# 1. Save the best model (Random Forest)
joblib.dump(best_model, 'defect_model.pkl')

# 2. Save the scaler (Crucial to avoid the 500 error)
joblib.dump(scaler, 'scaler.pkl')

# 3. Download both files
files.download('defect_model.pkl')
files.download('scaler.pkl')

